# Generated by Django 6.0.5 on 2026-05-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("date", models.CharField(blank=True, max_length=50)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
    ]
